export interface Database {
  public: {
    Tables: {
      eleves: {
        Row: {
          id: string;
          matricule: string;
          nom: string;
          postnom: string;
          prenom: string;
          sexe: string;
          lieu_naissance: string;
          date_naissance: string;
          section: string;
          option: string | null;
          responsable: string;
          telephone: string;
          domicile: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          matricule: string;
          nom: string;
          postnom: string;
          prenom: string;
          sexe: string;
          lieu_naissance: string;
          date_naissance: string;
          section: string;
          option?: string | null;
          responsable: string;
          telephone: string;
          domicile: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          matricule?: string;
          nom?: string;
          postnom?: string;
          prenom?: string;
          sexe?: string;
          lieu_naissance?: string;
          date_naissance?: string;
          section?: string;
          option?: string | null;
          responsable?: string;
          telephone?: string;
          domicile?: string;
          created_at?: string;
          updated_at?: string;
        };
      };
      minerval: {
        Row: {
          id: string;
          matricule: string;
          nom: string;
          postnom: string;
          prenom: string;
          sexe: string;
          lieu_naissance: string;
          date_naissance: string;
          section: string;
          option: string | null;
          responsable: string;
          telephone: string;
          domicile: string;
          montant_total: number;
          montant_paye: number;
          date_paiement: string;
          methode_paiement: string;
          numero_recu: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          matricule: string;
          nom: string;
          postnom: string;
          prenom: string;
          sexe: string;
          lieu_naissance: string;
          date_naissance: string;
          section: string;
          option?: string | null;
          responsable: string;
          telephone: string;
          domicile: string;
          montant_total?: number;
          montant_paye?: number;
          date_paiement?: string;
          methode_paiement?: string;
          numero_recu?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          matricule?: string;
          nom?: string;
          postnom?: string;
          prenom?: string;
          sexe?: string;
          lieu_naissance?: string;
          date_naissance?: string;
          section?: string;
          option?: string | null;
          responsable?: string;
          telephone?: string;
          domicile?: string;
          montant_total?: number;
          montant_paye?: number;
          date_paiement?: string;
          methode_paiement?: string;
          numero_recu?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      compte_courant: {
        Row: {
          id: string;
          montant_chiffre: number;
          montant_lettre: string;
          beneficiaire: string;
          libelle: string;
          telephone: string | null;
          type_operation: string;
          statut: string;
          date_transaction: string;
          created_at: string;
          nom_comptable: string | null;
          nom_approbateur: string | null;
        };
        Insert: {
          id?: string;
          montant_chiffre: number;
          montant_lettre: string;
          beneficiaire: string;
          libelle: string;
          telephone?: string | null;
          type_operation: string;
          statut?: string;
          date_transaction?: string;
          created_at?: string;
          nom_comptable?: string | null;
          nom_approbateur?: string | null;
        };
        Update: {
          id?: string;
          montant_chiffre?: number;
          montant_lettre?: string;
          beneficiaire?: string;
          libelle?: string;
          telephone?: string | null;
          type_operation?: string;
          statut?: string;
          date_transaction?: string;
          created_at?: string;
          nom_comptable?: string | null;
          nom_approbateur?: string | null;
        };
      };
      gestion_fournitures: {
        Row: {
          id: string;
          matricule: string;
          nom: string;
          postnom: string;
          prenom: string;
          sexe: string;
          lieu_naissance: string;
          date_naissance: string;
          section: string;
          option: string | null;
          annee: string;
          eps: boolean;
          pull: boolean;
          date_distribution: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          matricule: string;
          nom: string;
          postnom: string;
          prenom: string;
          sexe: string;
          lieu_naissance: string;
          date_naissance: string;
          section: string;
          option?: string | null;
          annee: string;
          eps?: boolean;
          pull?: boolean;
          date_distribution?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          matricule?: string;
          nom?: string;
          postnom?: string;
          prenom?: string;
          sexe?: string;
          lieu_naissance?: string;
          date_naissance?: string;
          section?: string;
          option?: string | null;
          annee?: string;
          eps?: boolean;
          pull?: boolean;
          date_distribution?: string | null;
          created_at?: string;
        };
      };
      gestion_fourniture_bureau: {
        Row: {
          id: string;
          article: string;
          beneficiaire: string;
          commentaire: string | null;
          quantite: number;
          date_operation: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          article: string;
          beneficiaire: string;
          commentaire?: string | null;
          quantite?: number;
          date_operation?: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          article?: string;
          beneficiaire?: string;
          commentaire?: string | null;
          quantite?: number;
          date_operation?: string;
          created_at?: string;
        };
      };
      paiements: {
        Row: {
          id: string;
          numero_recu: string;
          eleve_id: string;
          nom_eleve: string;
          matricule: string;
          postnom: string;
          prenom: string;
          classe: string;
          sexe: string;
          section: string;
          option: string | null;
          telephone: string;
          domicile: string;
          lieu_naissance: string | null;
          date_naissance: string | null;
          responsable: string | null;
          photo_url: string | null;
          type_paiement: string;
          description: string | null;
          montant_paye: number;
          montant_en_lettre: string;
          mode_paiement: string;
          date_paiement: string;
          comptable_id: string;
          nom_comptable: string;
          est_encaisse: boolean;
          date_encaissement: string | null;
          encaisseur_id: string | null;
          nom_encaisseur: string | null;
          annee_scolaire: string | null;
          motif_id: string | null;
          motif_libelle: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          numero_recu?: string;
          eleve_id: string;
          nom_eleve: string;
          matricule: string;
          postnom: string;
          prenom: string;
          classe: string;
          sexe: string;
          section: string;
          option?: string | null;
          telephone: string;
          domicile: string;
          lieu_naissance?: string | null;
          date_naissance?: string | null;
          responsable?: string | null;
          photo_url?: string | null;
          type_paiement: string;
          description?: string | null;
          montant_paye: number;
          montant_en_lettre: string;
          mode_paiement: string;
          date_paiement?: string;
          comptable_id: string;
          nom_comptable: string;
          est_encaisse?: boolean;
          date_encaissement?: string | null;
          encaisseur_id?: string | null;
          nom_encaisseur?: string | null;
          annee_scolaire?: string | null;
          motif_id?: string | null;
          motif_libelle?: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          numero_recu?: string;
          eleve_id?: string;
          nom_eleve?: string;
          matricule?: string;
          postnom?: string;
          prenom?: string;
          classe?: string;
          sexe?: string;
          section?: string;
          option?: string | null;
          telephone?: string;
          domicile?: string;
          lieu_naissance?: string | null;
          date_naissance?: string | null;
          responsable?: string | null;
          photo_url?: string | null;
          type_paiement?: string;
          description?: string | null;
          montant_paye?: number;
          montant_en_lettre?: string;
          mode_paiement?: string;
          date_paiement?: string;
          comptable_id?: string;
          nom_comptable?: string;
          est_encaisse?: boolean;
          date_encaissement?: string | null;
          encaisseur_id?: string | null;
          nom_encaisseur?: string | null;
          annee_scolaire?: string | null;
          motif_id?: string | null;
          motif_libelle?: string;
          created_at?: string;
        };
      };
    };
  };
}
